name: Build & Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build zip
        run: |
          zip -r "ra3valik-template-usage-${{ github.ref_name }}.zip" "ra3valik-template-usage"

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: ra3valik-template-usage-${{ github.ref_name }}.zip
